version: '3.7'

services:
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './.postgresql_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=PGPASS
    ports:
      - '5432:5432'

  app:
    build: .
    volumes:
      - .:/usr/src/app
    command: cargo run
    depends_on:
      - postgres
